version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: simple-keyboard
    versions:
    - 2.32.120
    - 2.32.89
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
